

#ifndef SORTING_ALGORITHM_VISUALIZED_CREATERANDOMDATA_H
#define SORTING_ALGORITHM_VISUALIZED_CREATERANDOMDATA_H

class createRandomData {};

#endif // SORTING_ALGORITHM_VISUALIZED_CREATERANDOMDATA_H
